// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokemonApp.Infrastructure;

#nullable disable

namespace PokemonApp.Infrastructure.Migrations
{
    [DbContext(typeof(PokemonDbContext))]
    partial class PokemonDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PokemonApp.Domain.Pokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pokemons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Level = 15,
                            Name = "Pikachu",
                            Type = "Electric"
                        },
                        new
                        {
                            Id = 2,
                            Level = 20,
                            Name = "Charmander",
                            Type = "Fire"
                        },
                        new
                        {
                            Id = 3,
                            Level = 8,
                            Name = "Squirtle",
                            Type = "Water"
                        },
                        new
                        {
                            Id = 4,
                            Level = 8,
                            Name = "Bulbasaur",
                            Type = "Grass"
                        },
                        new
                        {
                            Id = 5,
                            Level = 5,
                            Name = "Jigglypuff",
                            Type = "Fairy"
                        },
                        new
                        {
                            Id = 6,
                            Level = 20,
                            Name = "Snorlax",
                            Type = "Normal"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
